# Let's Configure Copperized
copper_axe = true
copper_bars = true
copper_boots = true
copper_button = true
copper_chestplate = true
copper_door = true
copper_helmet = true
copper_hoe = true
copper_horse_armor = true
copper_leggings = true
copper_nugget = true
copper_pickaxe = true
copper_shovel = true
copper_sword = true
copper_trapdoor = true
medium_weighted_pressure_plate = true

