
[Reach]
	#Reach: how far away the player can place blocks using mirror/array etc.
	#Enable the crafting of reach upgrades to increase reach.
	#If disabled, reach is set to level 3 for survival players.
	enableReachUpgrades = true
	#Maximum reach in creative
	#Keep in mind that chunks need to be loaded to be able to place blocks inside.
	#Range: 0 ~ 1000
	maxReachCreative = 200
	#Maximum reach in survival without upgrades
	#Reach upgrades are craftable consumables that permanently increase reach.
	#Set to 0 to disable Effortless Building until the player has consumed a reach upgrade.
	#Range: 0 ~ 1000
	maxReachLevel0 = 20
	#Maximum reach in survival with one upgrade
	#Range: 0 ~ 1000
	maxReachLevel1 = 50
	#Maximum reach in survival with two upgrades
	#Range: 0 ~ 1000
	maxReachLevel2 = 100
	#Maximum reach in survival with three upgrades
	#Range: 0 ~ 1000
	maxReachLevel3 = 200

[SurvivalBalancers]
	#Determines what blocks can be replaced in survival.
	#-1: only blocks that can be harvested by hand (default)
	#0: blocks that can be harvested with wooden or gold tools
	#1: blocks that can be harvested with stone tools
	#2: blocks that can be harvested with iron tools
	#3: blocks that can be harvested with diamond tools
	#4: blocks that can be harvested with netherite tools
	#Range: -1 ~ 3
	quickReplaceMiningLevel = -1

